x-veld:
  code:
    description:
    topic:
    additional:

    input:
      - volume: /veld/input/
        file_type:
        content:
        environemnt_var:

    output:
      - volume: /veld/output/
        file_type:
        content:
        environemnt_var:

    config:
      - environemnt_var:
        description:
        var_type:
        default:
        optional:

services:
  veld_train:
    build: .
    command: bash /veld/code/run.sh train
    ports:
      - 8888:8888
    volumes:
      - ./src/:/veld/code/
    environment:
      run_interactively: true

